services:
  - type: web
    name: tg-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: BOT_TOKEN
        sync: false
      - key: BASE_URL
        value: https://tg-bot.onrender.com
      - key: OWNER_ID
        value: "0"
      - key: ADMIN_IDS
        value: "8602669701,8984979728,5523283724,6904151750"
      - key: TZ
        value: Europe/Moscow